databaseChangeLog:
  - changeSet:
      id: product
      author: joel
      changes:
        - createTable:
            tableName: Product
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: varchar(25)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(150)
                  constraints:
                    nullable: false

